### ISSUE TITLE
task lists with wrapped lines have no hanging indent

### ISSUE THREAD

**Issue by diablodale** [mjbvz/vscode-markdown-checkboxes#5]
With a task list, where a task is very long, and is wrapped in the preview... the wrap has no hanging indent and is instead restarted at the beginning of the line.

## Repo
```markdown
- [ ] test 1
- [ ] test 2 fs sfddsafsdsfg afg afsgfdsg asfgsa afdgafdsgsfdg dfsgdsfg
  sfdg sdfgsdffdsg fda sdf adsfasfas fdsafsadf sadf sadfsadf asdf asf
  saf sadfasdf asdfsadfas fsdafasdf sadfsadf sadfsadf asdfsadf asdf
- [ ] test 3
```

## Errant Result

![image](https://user-images.githubusercontent.com/679350/41365472-bef7eed6-6f39-11e8-9819-bb1446ab074d.png)

## Expected

Here is the GitHub render. Notice the hanging indent on the second task

- [ ] test 1
- [ ] test 2 fs sfddsafsdsfg afg afsgfdsg asfgsa afdgafdsgsfdg dfsgdsfg
  sfdg sdfgsdffdsg fda sdf adsfasfas fdsafsadf sadf sadfsadf asdf asf
  saf sadfasdf asdfsadfas fsdafasdf sadfsadf sadfsadf asdfsadf asdf
- [ ] test 3

## Notes

I found over https://gist.github.com/BigstickCarpet/5d31c053d0b1d52389eb2723f7550907 three css styles which would better match GitHub if I used them with the custom user setting `"markdown.styles"`. I needed to tweak them a little. Here's what is working for me.

```css
body .task-list-item {
    list-style-type: none;
    padding-left: 42px;
    padding-right: 15px;
    margin-left: -15px;
    margin-right: -15px;
}

body .task-list-item+.task-list-item {
    margin-top: 0;
}

body .task-list-item input {
    list-style-type: none;
    text-align: start;
    padding: 0;
    margin: 0 2.8px 3.5px -22.4px;
}
```
